wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1680227504.961842
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.16
      5: 0.14.0
      8:
      - 5
deform_layers:
  desc: null
  value:
  - false
  - false
  - false
  - true
  - true
num_layers:
  desc: null
  value: 5
